#! /bin/bash


DOMAIN_PROPERTY_FILE=../config/domain.properties


# Uses --source-dir
# CAMEL_START_PLANNER="jbang camel@apache/camel run --name planner --background --source-dir=../camel/chat-agent-advanced --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0 --logging-level=info"
# CAMEL_START_AGENT="jbang camel@apache/camel run --name agent --background --source-dir=../camel/chat-agent-basic --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0 --logging-level=info"
# CAMEL_START_DASHBOARD="jbang camel@apache/camel run --name dashboard --background --source-dir=../camel/admin-dashboard --logging-level=info"
# CAMEL_START_TRANSCRIPTS="jbang camel@apache/camel run --name transcripts --background --source-dir=../camel/ingest-transcripts --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0 --logging-level=info"

# JBang command
# CAMEL_START_PLANNER="jbang camel@apache/camel run * --name planner --background --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0 --logging-level=info"
# CAMEL_START_AGENT="jbang camel@apache/camel run * --name agent --background --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0 --logging-level=info"
# CAMEL_START_DASHBOARD="camel run * --name dashboard --background --logging-level=info"
# CAMEL_START_TRANSCRIPTS="jbang camel@apache/camel run * --name transcripts --background --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0 --logging-level=info"

# Camel JBang
# CAMEL_START_PLANNER="camel run * --name planner --background --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0 --logging-level=info"
# CAMEL_START_AGENT="camel run * --name agent --background --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0 --logging-level=info"
# CAMEL_START_DASHBOARD="camel run * --name dashboard --background --logging-level=info"
# CAMEL_START_TRANSCRIPTS="camel run * --name transcripts --background --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0 --logging-level=info"

# no names
CAMEL_START_PLANNER="camel run * ../$DOMAIN_PROPERTY_FILE --background --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0 --logging-level=info"
CAMEL_START_AGENT="camel run * ../$DOMAIN_PROPERTY_FILE --background --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0 --logging-level=info"
CAMEL_START_DASHBOARD="camel run * ../$DOMAIN_PROPERTY_FILE --background --logging-level=info"
CAMEL_START_TRANSCRIPTS="camel run * ../$DOMAIN_PROPERTY_FILE --background --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0 --logging-level=info"
CAMEL_START_INGEST="camel run --background --source-dir=../camel/ingest-invoices --properties=$DOMAIN_PROPERTY_FILE --dep=dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0"
CAMEL_START_X12="camel run --background * ../$DOMAIN_PROPERTY_FILE"



eval "./agents-down"



# =====================
# Using --source-dir
# =====================
# echo "Starting planner..."
# eval "$CAMEL_START_PLANNER"

# echo "Starting agent..."
# eval "$CAMEL_START_AGENT"

# echo "Starting dashboard..."
# eval "$CAMEL_START_DASHBOARD"

# # echo "Starting transcripts..."
# eval "$CAMEL_START_TRANSCRIPTS"



# =====================
# Using 'cd'
# =====================
echo "Starting planner..."
cd ../camel/chat-agent-advanced
eval "$CAMEL_START_PLANNER"
cd $OLDPWD

echo "Starting agent..."
cd ../camel/chat-agent-basic
eval "$CAMEL_START_AGENT"
cd $OLDPWD

echo "Starting admin..."
cd ../camel/admin-dashboard
eval "$CAMEL_START_DASHBOARD"
cd $OLDPWD

echo "Starting transcripts..."
cd ../camel/ingest-transcripts
eval "$CAMEL_START_TRANSCRIPTS"
cd $OLDPWD


# =======================
# No HTML pages to serve
# =======================
# echo "Starting invoices ingestion..."
eval "$CAMEL_START_INGEST"

# echo "Starting X12 ingestion..."
# eval "$CAMEL_START_X12"
echo "Starting X12 ingestion..."
cd ../camel/ingest-x12
eval "$CAMEL_START_X12"
cd $OLDPWD

eval "camel ps"
