<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <X12_850>
            <Header>
                <ISA>
                    <ISA-01>
                        <xsl:value-of select="'00'"/>
                    </ISA-01>
                    <ISA-02>
                        <xsl:value-of select="'          '"/>
                    </ISA-02>
                    <ISA-03>
                        <xsl:value-of select="'00'"/>
                    </ISA-03>
                    <ISA-04>
                        <xsl:value-of select="'          '"/>
                    </ISA-04>
                    <ISA-05>
                        <xsl:value-of select="'01'"/>
                    </ISA-05>
                    <ISA-06>
                        <xsl:value-of select="/Invoice/Client/TaxId"/>
                    </ISA-06>
                    <ISA-07>
                        <xsl:value-of select="'01'"/>
                    </ISA-07>
                    <ISA-08>
                        <xsl:value-of select="/Invoice/Seller/TaxId"/>
                    </ISA-08>
                    <ISA-09>
                        <xsl:value-of select="/Invoice/DateOfIssue"/>
                    </ISA-09>
                    <ISA-10>
                        <xsl:value-of select="'1200'"/>
                    </ISA-10>
                    <ISA-11>
                        <xsl:value-of select="'U'"/>
                    </ISA-11>
                    <ISA-12>
                        <xsl:value-of select="'00401'"/>
                    </ISA-12>
                    <ISA-13>
                        <xsl:value-of select="'000000001'"/>
                    </ISA-13>
                    <ISA-14>
                        <xsl:value-of select="'0'"/>
                    </ISA-14>
                    <ISA-15>
                        <xsl:value-of select="'P'"/>
                    </ISA-15>
                    <ISA-16>
                        <xsl:value-of select="':'"/>
                    </ISA-16>
                </ISA>
                <GS>
                    <GS-01>
                        <xsl:value-of select="'PO'"/>
                    </GS-01>
                    <GS-02>
                        <xsl:value-of select="/Invoice/Seller/TaxId"/>
                    </GS-02>
                    <GS-03>
                        <xsl:value-of select="/Invoice/Client/TaxId"/>
                    </GS-03>
                    <GS-04>
                        <xsl:value-of select="/Invoice/DateOfIssue"/>
                    </GS-04>
                    <GS-05>
                        <xsl:value-of select="'1200'"/>
                    </GS-05>
                    <GS-06>
                        <xsl:value-of select="'1'"/>
                    </GS-06>
                    <GS-07>
                        <xsl:value-of select="'X'"/>
                    </GS-07>
                    <GS-08>
                        <xsl:value-of select="'004010'"/>
                    </GS-08>
                </GS>


                <ST>
                    <ST-01>
                        <xsl:value-of select="'850'"/>
                    </ST-01>
                    <ST-02>
                        <xsl:value-of select="'0001'"/>
                    </ST-02>
                </ST>
                <BEG>
                    <BEG-01>
                        <xsl:value-of select="'00'"/>
                    </BEG-01>
                    <BEG-02>
                        <xsl:value-of select="'SA'"/>
                    </BEG-02>
                    <BEG-03>
                        <xsl:value-of select="/Invoice/InvoiceNumber"/>
                    </BEG-03>
                    <BEG-05>
                        <xsl:value-of select="/Invoice/DateOfIssue"/>
                    </BEG-05>
                </BEG>
               
                <N1Loop>
                    <N1>
                        <N1-01>
                            <xsl:value-of select="'BY'"/>
                        </N1-01>
                        <N1-02>
                            <xsl:value-of select="/Invoice/Seller/Name"/>
                        </N1-02>
                        <N1-03>
                            <xsl:value-of select="91"/>
                        </N1-03>
                        <N1-04>
                            <xsl:value-of select="/Invoice/Seller/TaxId"/>
                        </N1-04>
                    </N1>
                    <N3>
                        <N3-01>
                            <xsl:value-of select="/Invoice/Seller/Address/Street"/>
                        </N3-01>
                    </N3>
                    <N4>
                        <N4-01>
                            <xsl:value-of select="/Invoice/Seller/Address/City"/>
                        </N4-01>
                        <N4-02>
                            <xsl:value-of select="/Invoice/Seller/Address/State"/>
                        </N4-02>
                        <N4-03>
                            <xsl:value-of select="/Invoice/Seller/Address/PostalCode"/>
                        </N4-03>
                    </N4>
                </N1Loop>
                <N1Loop>
                    <N1>
                        <N1-01>
                            <xsl:value-of select="'SE'"/>
                        </N1-01>
                        <N1-02>
                            <xsl:value-of select="/Invoice/Client/Name"/>
                        </N1-02>
                        <N1-03>
                            <xsl:value-of select="91"/>
                        </N1-03>
                        <N1-04>
                            <xsl:value-of select="/Invoice/Client/TaxId"/>
                        </N1-04>
                    </N1>
                    <N3>
                        <N3-01>
                            <xsl:value-of select="/Invoice/Client/Address/Street"/>
                        </N3-01>
                    </N3>
                    <N4>
                        <N4-01>
                            <xsl:value-of select="/Invoice/Client/Address/City"/>
                        </N4-01>
                        <N4-02>
                            <xsl:value-of select="/Invoice/Client/Address/State"/>
                        </N4-02>
                        <N4-03>
                            <xsl:value-of select="/Invoice/Client/Address/PostalCode"/>
                        </N4-03>
                    </N4>
                </N1Loop>

                <N9Loop>
                    <N9>
                        <N9-01>
                            <xsl:value-of select="'IB'"/>
                        </N9-01>
                        <N9-02>
                            <xsl:value-of select="/Invoice/Seller/IBAN"/>
                        </N9-02>
                    </N9>
                </N9Loop>
            </Header>
            <xsl:for-each select="/Invoice/Items/Item">
                <PO1Loop>
                    <PO1>
                        <PO1-01>
                            <xsl:value-of select="Number"/>
                        </PO1-01>
                        <PO1-02>
                            <xsl:value-of select="Quantity"/>
                        </PO1-02>
                        <xsl:if test="UnitOfMeasure=&quot;Each&quot;">
                            <PO1-03>
                                <xsl:value-of select="'EA'"/>
                            </PO1-03>
                        </xsl:if>
                        <PO1-04>
                            <xsl:value-of select="NetPrice"/>
                        </PO1-04>
                        <PO1-05>
                            <xsl:value-of select="'QT'"/>
                        </PO1-05>
                        <PO1-06>
                            <xsl:value-of select="'SK'"/>
                        </PO1-06>
                        <PO1-07>
                            <xsl:value-of select="ProductID"/>
                        </PO1-07>
                    </PO1>
                    <PIDLoop>
                        <PID>
                            <PID-01>
                                <xsl:value-of select="'F'"/>
                            </PID-01>
                            <PID-05>
                                <xsl:value-of select="Description"/>
                            </PID-05>
                        </PID>
                    </PIDLoop>
                </PO1Loop>
            </xsl:for-each>


            <!-- <CTT>
                <CTT-01>4</CTT-01>
                <CTT-02>11</CTT-02>
            </CTT>
            <AMT>
                <AMT-01>TT</AMT-01>
                <AMT-02>212.09</AMT-02>
            </AMT>
            <SE>
                <SE-01>15</SE-01>
                <SE-02>0001</SE-02>
            </SE>
            <GE>
                <GE-01>1</GE-01>
                <GE-02>1</GE-02>
            </GE>
            <IEA>
                <IEA-01>1</IEA-01>
                <IEA-02>000000001</IEA-02>
            </IEA> -->


            <CTT>
                <CTT-01>
                    <xsl:value-of select="count(/Invoice/Items/Item)"/>
                </CTT-01>
                <CTT-02>
                    <xsl:value-of select="sum(/Invoice/Items/Item/Quantity)"/>
                </CTT-02>
            </CTT>
            <AMT>
                <AMT-01>
                    <xsl:value-of select="'TT'"/>
                </AMT-01>
                <AMT-02>
                    <xsl:value-of select="/Invoice/Summary/GrossWorth"/>
                </AMT-02>
            </AMT>
            <SE>
                <SE-01>
                    <xsl:value-of select="'15'"/>
                </SE-01>
                <SE-02>
                    <xsl:value-of select="'0001'"/>
                </SE-02>
            </SE>
            <GE>
                <GE-01>
                    <xsl:value-of select="'1'"/>
                </GE-01>
                <GE-02>
                    <xsl:value-of select="'1'"/>
                </GE-02>
            </GE>
            <IEA>
                <IEA-01>
                    <xsl:value-of select="'1'"/>
                </IEA-01>
                <IEA-02>
                    <xsl:value-of select="'000000001'"/>
                </IEA-02>
            </IEA>

        </X12_850>
    </xsl:template>
</xsl:stylesheet>